### ISSUE TITLE
npm ERR! Error: ENOENT, open '/Users/alukos/proj/pms-stub/node_modules/build/package.json'

### ISSUE THREAD

**Issue by alukos** [nin-jin/pms-stub#2]
Склонировал, установил - ругнулся 
```
$ npm install
...
npm http GET https://registry.npmjs.org/arr-diff/-/arr-diff-2.0.0.tgz
module.js:340
    throw err;
          ^
Error: Cannot find module 'npmlog'
...
```
```
$ npm start build mol
npm ERR! Error: ENOENT, open '/Users/alukos/proj/pms-stub/node_modules/build/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "start" "build" "mol"
npm ERR! cwd /Users/alukos/proj/pms-stub
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /Users/alukos/proj/pms-stub/node_modules/build/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/alukos/proj/pms-stub/npm-debug.log
npm ERR! not ok code 0
```

**Comment by nin-jin** [comment]
Какая версия npm и node?

**Comment by alukos** [comment]
Были node -v v0.10.21, npm -v 1.3.11
Снес, установил через homebrew node v6.0, v5.5 - не завелось
Еще сборка другого проекта сломалась.
С какой должно работать? 6.0, 6.1?

**Comment by nin-jin** [comment]
Судя по всему, у вас криво поставился какой-то из нодовских модулей. Пробовали удалить node_modules и повторить процедуру?

С последними версиями node и npm на windows всё собирается (сейчас внёс пару патчей для совместимости с новой нодой).

Также первые билды могут падать с сообщениями вида "Execution of [git clone https://github.com/nin-jin/pms-jin2.git ./jin2] ends with code 128" - после нескольких запусков они должны проходить.

**Comment by alukos** [comment]
Попробовал удалить node_modules, переустановил
Ошибка почти та же:
```
$ npm start build mol

> pms-stub@1.0.0 start /Users/alukos/proj/pms-stub
> pms "build" "mol"

12:31:02 $jin.build..jsCompiled.pull 'jin/build/-mix/index.env=node.stage=release.js'
12:31:02 callback TypeError: Constructor Proxy requires 'new'
    at /Users/alukos/proj/pms-stub/jin/proxy/jin_proxy.jam.js:7:1
    at Object.$jin.method.$jin.async2sync (/Users/alukos/proj/pms-stub/jin/async2sync/jin_async2sync.env=node.jam.js:80:1)
    at Object.<anonymous> (/Users/alukos/proj/pms-stub/jin/alert/jin-alert.env=node.jam.js:1:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "start" "build" "mol"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! pms-stub@1.0.0 start: `pms "build" "mol"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pms-stub@1.0.0 start script 'pms "build" "mol"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pms-stub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pms "build" "mol"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pms-stub
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pms-stub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alukos/proj/pms-stub/npm-debug.log
```

**Comment by nin-jin** [comment]
Нужно удалить директорию jin или вручную сделать в ней git pull.

**Comment by alukos** [comment]
все удалил, заново склонировал `npm install`
```
$ npm start build mol

> pms-stub@1.0.0 start /Users/alukos/proj/pms-stub
> pms "build" "mol"

15:11:54 $jin.file.base..require Module (/Users/alukos/proj/pms-stub/jin) not found. Search (jin) in repository...
{ type: 'git', url: 'https://github.com/nin-jin/pms-jin.git' }
15:11:56 $jin.file.base..require Installing (/Users/alukos/proj/pms-stub/jin) from (https://github.com/nin-jin/pms-jin.git)...
Cloning into '/Users/alukos/proj/pms-stub/jin'...
remote: Counting objects: 2088, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 2088 (delta 0), reused 0 (delta 0), pack-reused 2084
Receiving objects: 100% (2088/2088), 398.52 KiB | 372.00 KiB/s, done.
Resolving deltas: 100% (1041/1041), done.
Checking connectivity... done.
15:11:59 $jin.build..jsCompiled.pull 'jin/build/-mix/index.env=node.stage=release.js'
15:11:59  Building 'mol?env=web&stage=test'
15:11:59 $jin.file.base..require Module (/Users/alukos/proj/pms-stub/mol) not found. Search (mol) in repository...
{ type: 'git', url: 'git+https://github.com/nin-jin/mol.git' }
15:12:00 $jin.file.base..require Installing (/Users/alukos/proj/pms-stub/mol) from (https://github.com/nin-jin/mol.git)...
Cloning into '/Users/alukos/proj/pms-stub/mol'...
remote: Counting objects: 857, done.
remote: Total 857 (delta 0), reused 0 (delta 0), pack-reused 856
Receiving objects: 100% (857/857), 129.00 KiB | 127.00 KiB/s, done.
Resolving deltas: 100% (455/455), done.
Checking connectivity... done.
15:12:03 $jin.build..jsCompiled.pull 'mol/-mix/index.env=web.stage=test.js'
15:12:05 $jin.atom1.._fail TypeError: Cannot read property 'type' of null
    at new LazyResult (/Users/alukos/proj/pms-stub/node_modules/postcss/lib/lazy-result.js:45:90)
    at Processor.process (/Users/alukos/proj/pms-stub/node_modules/postcss/lib/processor.js:34:16)
    at jin_trait_instance.$jin.atom1.prop.list.$jin.build..cssCompiled.pull (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:6775:26)
    at jin_trait_instance.$jin.method.$jin.atom1.pullable..pull (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:1339:25)
    at jin_trait_instance.$jin.method.$jin.atom1.pullable..get (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:1295:41)
    at jin_trait_instance.$jin.method.$jin.atom1.getable..get (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:1505:46)
    at jin_trait_instance.jin_atom_prop_accessor (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:2671:45)
    at /Users/alukos/proj/pms-stub/node_modules/pms/bin/pms:16:26
    at proc (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:1993:22)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "start" "build" "mol"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! pms-stub@1.0.0 start: `pms "build" "mol"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pms-stub@1.0.0 start script 'pms "build" "mol"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pms-stub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pms "build" "mol"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pms-stub
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pms-stub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alukos/proj/pms-stub/npm-debug.log
```

**Comment by nin-jin** [comment]
Повторный запуск не помогает?

**Comment by alukos** [comment]
Три повторных запуска помогли - сбилдились
Сервер не запускается.
```
$ npm start serve

> pms-stub@1.0.0 start /Users/alukos/proj/pms-stub
> pms "serve"

10:35:13  Serving 'http://127.0.0.1:80'
Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at Server._listen2 (net.js:1233:19)
    at listen (net.js:1282:10)
    at Server.listen (net.js:1378:5)
    at EventEmitter.listen (/Users/alukos/proj/pms-stub/node_modules/express/lib/application.js:617:24)
    at /Users/alukos/proj/pms-stub/node_modules/pms/bin/pms:23:24
    at proc (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:1993:22)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/Users/alukos/proj/pms-stub/node_modules/.bin/npm" "start" "serve"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! pms-stub@1.0.0 start: `pms "serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pms-stub@1.0.0 start script 'pms "serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pms-stub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pms "serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pms-stub
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pms-stub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alukos/proj/pms-stub/npm-debug.log
```

**Comment by nin-jin** [comment]
http://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports

**Comment by alukos** [comment]
попробовал через sudo:
```
$ sudo npm start serve
Password:

> pms-stub@1.0.0 start /Users/alukos/proj/pms-stub
> pms "serve"

14:46:41  Serving 'http://127.0.0.1:80'
Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at Server._listen2 (net.js:1246:14)
    at listen (net.js:1282:10)
    at Server.listen (net.js:1378:5)
    at EventEmitter.listen (/Users/alukos/proj/pms-stub/node_modules/express/lib/application.js:617:24)
    at /Users/alukos/proj/pms-stub/node_modules/pms/bin/pms:23:24
    at proc (/Users/alukos/proj/pms-stub/node_modules/pms/index.env=node.stage=release.js:1993:22)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/Users/alukos/proj/pms-stub/node_modules/.bin/npm" "start" "serve"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! pms-stub@1.0.0 start: `pms "serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pms-stub@1.0.0 start script 'pms "serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pms-stub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pms "serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pms-stub
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pms-stub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alukos/proj/pms-stub/npm-debug.log
```

**Comment by nin-jin** [comment]
На этом порту уже запущен другой сервер. Его надо остановить.

**Comment by alukos** [comment]
Ура! завелось :)
